"""Changes in my table 

Revision ID: 256f22848ca1
Revises: 90bc08e0627e
Create Date: 2025-06-14 11:35:35.330985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256f22848ca1'
down_revision: Union[str, None] = '90bc08e0627e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verificationcode', sa.Column('name', sa.String(), nullable=False))
    op.add_column('verificationcode', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verificationcode', 'password')
    op.drop_column('verificationcode', 'name')
    # ### end Alembic commands ###
