"""Changes in verificationcode

Revision ID: c78b40c5c7ee
Revises: c8a646e1dc8a
Create Date: 2025-06-16 23:31:12.059180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78b40c5c7ee'
down_revision: Union[str, None] = 'c8a646e1dc8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verificationcode', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'verificationcode', 'users', ['user_id'], ['id'])
    op.drop_column('verificationcode', 'email')
    op.drop_column('verificationcode', 'password')
    op.drop_column('verificationcode', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verificationcode', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('verificationcode', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('verificationcode', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'verificationcode', type_='foreignkey')
    op.drop_column('verificationcode', 'user_id')
    # ### end Alembic commands ###
