"""Change todo table columns

Revision ID: e9ebf7f220f9
Revises: 74704c324c0e
Create Date: 2025-05-30 20:42:13.762071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ebf7f220f9'
down_revision: Union[str, None] = '74704c324c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('todo', sa.Column('category', sa.String(), nullable=False))
    op.create_foreign_key(None, 'todo', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'category')
    op.drop_column('todo', 'user_id')
    # ### end Alembic commands ###
